name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag"
        required: false
        type: string
      publish:
        description: "Set r for release, p for prerelease, leave empty to skip publishing"
        required: false
        default: ""
        type: string

jobs:
  build:
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: windows-latest
            qt_version: "6.11.0"
            target: x64
            dest_suffix: windows-amd64

          # - platform: windows-11-arm
          #   qt_version: "6.11.0"
          #   target: arm64
          #   dest_suffix: windows-arm64

          - platform: ubuntu-22.04
            qt_version: "6.11.0"
            target: x86_64
            dest_suffix: linux-amd64

          # - platform: ubuntu-24.04-arm
          #   qt_version: "6.11.0"
          #   target: aarch64
          #   dest_suffix: linux-arm64
    runs-on: ${{ matrix.platform }}

    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      INPUT_VERSION: ${{ github.event.inputs.tag }}
      DEST: ${{ github.workspace }}/deployment/${{ matrix.dest_suffix }}
      DEST_SUFFIX: ${{ matrix.dest_suffix }}
      ARCH: ${{ matrix.target }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSVC
        if: contains(matrix.platform, 'windows')
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Install Qt
        if: "!contains(matrix.platform, 'windows')"
        uses: jurplel/install-qt-action@v4.3.1
        with:
          version: ${{ matrix.qt_version }}
          setup-python: true
          cache: true
          cache-key-prefix: QtCache-${{ matrix.dest_suffix }}

      # ================= Configure =================

      - name: Windows - Configure
        if: contains(matrix.platform, 'windows')
        shell: bash
        run: |
          curl -L -o qt.7z https://github.com/throneproj/buildqt/releases/download/Qt_${{ matrix.qt_version }}/Qt_${{ matrix.qt_version }}_${{ matrix.target }}.7z
          7z x qt.7z
          export CMAKE_PREFIX_PATH="$PWD/Qt/lib/cmake"
          mkdir -p build
          cd build

          cmake -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
          ninja

          rm -rf $DEST
          mkdir -p $DEST
          cp $GITHUB_WORKSPACE/build/proxy-converter.exe $DEST
          cp $GITHUB_WORKSPACE/build/proxy-converter.pdb $DEST || true

      - name: Linux - Configure
        if: "!contains(matrix.platform, 'windows')"
        shell: bash
        run: |
          mkdir -p build
          cd build

          cmake -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_EXE_LINKER_FLAGS="-static-libgcc -static-libstdc++" ..
          ninja
          
          cd ..
          ./script/deploy_linux64.sh

      - name: Tar files
        shell: bash
        run: tar czvf artifacts.tgz ./deployment
      - name: Uploading Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: proxy-converter-${{ github.sha }}-${{ matrix.dest_suffix }}
          path: artifacts.tgz

  publish:
    name: Pack & Publish Release
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      contents: write
      actions: read
    steps:
      - name: Checking out sources
        uses: actions/checkout@v4.2.2
      - name: Download Artifacts
        uses: actions/download-artifact@v4.3.0
        with:
          path: download-artifact
      - name: Pack
        run: |
          curl -Lo - https://github.com/tcnksm/ghr/releases/download/v0.17.0/ghr_v0.17.0_linux_amd64.tar.gz | tar xzv
          mv ghr*linux_amd64/ghr .
          find . -name artifacts.tgz | xargs -n1 tar xvzf
          cd deployment
          mkdir debug
          ####
          mv linux-amd64 proxy-converter
          mv proxy-converter/proxy-converter.debug debug/proxy-converter-${{ github.event.inputs.tag }}-linux-amd64.debug
          zip -9 -r proxy-converter-${{ github.event.inputs.tag }}-linux-amd64.zip proxy-converter
          rm -rf proxy-converter
          ####
          mv linux-arm64 proxy-converter
          mv proxy-converter/proxy-converter.debug debug/proxy-converter-${{ github.event.inputs.tag }}-linux-arm64.debug
          zip -9 -r proxy-converter-${{ github.event.inputs.tag }}-linux-arm64.zip proxy-converter
          rm -rf proxy-converter
          ####
          mv proxy-converterSetup.exe proxy-converter-${{ github.event.inputs.tag }}-windows64-installer.exe
          mv windows-amd64 proxy-converter
          mv proxy-converter/proxy-converter.pdb debug/proxy-converter-${{ github.event.inputs.tag }}-windows-amd64.pdb
          zip -9 -r proxy-converter-${{ github.event.inputs.tag }}-windows64.zip proxy-converter
          rm -rf proxy-converter
          ####
          mv windows-arm64 proxy-converter
          mv proxy-converter/proxy-converter.pdb debug/proxy-converter-${{ github.event.inputs.tag }}-windows-arm64.pdb
          zip -9 -r proxy-converter-${{ github.event.inputs.tag }}-windows-arm64.zip proxy-converter
          rm -rf proxy-converter
          ####
          zip -9 -r debug-symbols.zip debug
      - name: Uploading Debug Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Debug-${{ github.sha }}
          path: deployment/debug-symbols.zip
      - name: Clean Up
        run: |
          cd deployment
          rm -rf windows-amd64
          rm -rf windows-arm64
          rm -rf linux-amd64
          rm -rf linux-arm64
          rm -rf *.pdb
          rm -rf debug*
      - name: Uploading Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Deployment-${{ github.sha }}
          path: deployment
      - name: PreRelease
        if: github.event.inputs.publish == 'p'
        run: |
          ./ghr -prerelease -delete -c ${{ github.sha }} -t "${{ github.token }}" -n "${{ github.event.inputs.tag }}" "${{ github.event.inputs.tag }}" deployment
      - name: Release
        if: github.event.inputs.publish == 'r'
        run: |
          ./ghr -delete -c ${{ github.sha }} -t "${{ github.token }}" -n "${{ github.event.inputs.tag }}" "${{ github.event.inputs.tag }}" deployment